version: '3.8'
services:
  alpha_simulator_bot:
    build:
      context: ../  # 构建上下文指向根目录
      dockerfile: Dockerfile  # 指定根目录下的 Dockerfile
    volumes:
      - ../logs:/logs
      - ../data:/app/data
      - ../config:/config
      - ../output:/output
      - ../output:/app/output
    command: python main.py
    stop_grace_period: 60s  # 设置 60 秒超时
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 👈 让容器能通过这个名字访问宿主机
    ports:
      - "5001:5001"  # 👈 把容器的 5001 映射到宿主机的 5001